# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

cache:
  - web/node_modules
  - native/node_modules

install:
  - pushd web && npm install && popd web

test_script:
  - echo hello world
